#!/bin/sh
#
# /etc/X11/Xsession.d/98-lightdm-session-locales
#
# check user selected  session locale
#
if pidof -q lightdm; then
   DMRC="/var/lib/AccountsService/users/$USER"
   if pidof -q accounts-daemon && [ -r "$DMRC" ]; then
      : 
   else
      DMRC="$HOME/.dmrc"
   fi
   if [ -r $DMRC  ]; then
      DMRC_LANG=$(sed -nr '/^Language=/{s///g; s/utf8/UTF-8/p; q}' "$DMRC")
      if [ x"$DMRC_LANG" != "x" ]; then
         export LANG="$DMRC_LANG"
         export GDM_LANG="$DMRC_LANG"
         # papersize
         case $(locale -c -k LC_PAPER |sed -nr 's/height=|width=//p' | tr $'\n' 'x') in
            297x210x) export PAPERSIZE="a4"     ;;
           #279x216x) export PAPERSIZE="letter" ;;
                   *) export PAPERSIZE="letter" ;;
         esac
      fi
   fi
fi
